### ISSUE TITLE
training process some problems?

### ISSUE THREAD

**Issue by Gzzgz** [open-mmlab/mmhuman3d#103]
hello，when my input this "python tools/train.py configs/spin/tmp.py --gpus 2 --no-validate" for training and error is that:

AssertionError: MMDataParallel only supports single GPU training, if you need to train with multiple GPUs, please use MMDistributedDataParallel instead.

when input "python tools/train.py configs/spin/tmp.py --gpus 1 --no-validate" and get error is that:

Traceback (most recent call last):
  File "tools/train.py", line 154, in <module>
    main()
  File "tools/train.py", line 150, in main
    meta=meta)
  File "/root/cloud/lj28/project/git-code/mmhuman3d/mmhuman3d/apis/train.py", line 167, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/envs/open-mmpose/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/envs/open-mmpose/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/opt/conda/envs/open-mmpose/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/opt/conda/envs/open-mmpose/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/root/cloud/lj28/project/git-code/mmhuman3d/mmhuman3d/models/architectures/mesh_estimator.py", line 143, in train_step
    features = self.backbone(img)
  File "/opt/conda/envs/open-mmpose/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/cloud/lj28/project/git-code/mmhuman3d/mmhuman3d/models/backbones/resnet.py", line 620, in forward
    x = self.norm1(x)
  File "/opt/conda/envs/open-mmpose/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/open-mmpose/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 519, in forward
    world_size = torch.distributed.get_world_size(process_group)
  File "/opt/conda/envs/open-mmpose/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 625, in get_world_size
    return _get_group_size(group)
  File "/opt/conda/envs/open-mmpose/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 220, in _get_group_size
    _check_default_pg()
  File "/opt/conda/envs/open-mmpose/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 211, in _check_default_pg
    "Default process group is not initialized"
AssertionError: Default process group is not initialized

thx!

**Comment by mingyuan-zhang** [comment]
For training with 2 GPUs, you can use `slurm_train.sh` or `dist_train.sh` (which is merged recently). 

As for training hmr with single GPU, Sync_bn can not be used. You can remove this line from the config file.

https://github.com/open-mmlab/mmhuman3d/blob/561f271cff941a7ed4196fa4126bc747f1b4c1fb/configs/hmr/resnet50_hmr_pw3d.py#L31

**Comment by Gzzgz** [comment]
OK. THX
