### ISSUE TITLE
training with val, but  TypeError: evaluate() got an unexpected keyword argument 'logger'

### ISSUE THREAD

**Issue by Gzzgz** [open-mmlab/mmhuman3d#109]
raceback (most recent call last):
  File "tools/train.py", line 158, in <module>
    if __name__ == '__main__':
  File "tools/train.py", line 146, in main
    # add an attribute for visualization convenience
  File "/root/Downloads/mmhuman3d-0.4.0/mmhuman3d/apis/train.py", line 167, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "/root/anaconda3/envs/zxh/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/root/anaconda3/envs/zxh/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/root/anaconda3/envs/zxh/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/root/anaconda3/envs/zxh/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/root/anaconda3/envs/zxh/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 505, in _do_evaluate
    key_score = self.evaluate(runner, results)
  File "/root/anaconda3/envs/zxh/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 361, in evaluate
    eval_res = self.dataloader.dataset.evaluate(
TypeError: evaluate() got an unexpected keyword argument 'logger'
Traceback (most recent call last):
  File "/root/anaconda3/envs/zxh/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/zxh/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/envs/zxh/lib/python3.8/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/root/anaconda3/envs/zxh/lib/python3.8/site-packages/torch/distributed/launch.py", line 256, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/root/anaconda3/envs/zxh/bin/python', '-u', 'tools/train.py', '--local_rank=1', 'configs/lj28/mthmr/resnet50_mthmr_pw3d.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

val just like test in config:

    val=dict(
        type=dataset_type,
        body_model=dict(
            type='GenderedSMPL',
            keypoint_src='h36m',
            keypoint_dst='h36m',
            model_path='data/body_models/smpl',
            joints_regressor='data/body_models/J_regressor_h36m.npy'),
        dataset_name='pw3d',
        data_prefix='data',
        pipeline=test_pipeline,
        ann_file='pw3d_test.npz'),

THX!

**Comment by ttxskk** [comment]
Hi @Gzzgz , please pull the latest main. #90 might have fixed it.

**Comment by Gzzgz** [comment]
OK.THX
