### ISSUE TITLE
KeyError: 'features' at HMR demo

### ISSUE THREAD

**Issue by rlleshi** [open-mmlab/mmhuman3d#123]
Demo Command:

`python demo/etimate_smpl_video.py configs/hmr/resnet50_hmr_pw3d.py data/checkpoints/resnet50_hmr_pw3d-04f40f58_20211201.pth --single_person_demo --det_config demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py --det_checkpoint data/checkpoints/detection/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth --input_path work_dir/video.mp4 --output work_dir/results/ --show_path work_dir/results/ --smooth_type savgol --draw_bbox`

Get the following error @inference:

```
  File "demo/etimate_smpl_video.py", line 337, in <module>
    main(args)
  File "demo/etimate_smpl_video.py", line 241, in main
    single_person_with_mmdet(args, frames_iter)
  File "demo/etimate_smpl_video.py", line 91, in single_person_with_mmdet
    mesh_results = inference_video_based_model(
  File "mmhuman3d/mmhuman3d/apis/inference.py", line 244, in inference_video_based_model
    feature_sequences = _collate_feature_sequence(input_features,
  File "mmhuman3d/apis/inference.py", line 465, in _collate_feature_sequence
    C = extracted_features[target_frame][0]['features'].shape[0]
KeyError: 'features'

```

Same error for `SPIN`

P. S. 
The the config for both `hmr` & `spin` is missing `data.test.seq_len`.

**Comment by ttxskk** [comment]
Hi @rlleshi, you should run `demo/estimate_smpl_image.py` when demoing HMR or SPIN. Video here refers to video-based methods such as VIBE.

**Comment by rlleshi** [comment]
Right..., thanks!

One more thing, I am running out of memory on 32g (with both models).  What can I tune to fix this?

**Comment by ttxskk** [comment]
Hi @rlleshi, can you provide more details like the frame count of your demo video?

**Comment by rlleshi** [comment]
It is running out of memory when trying to save the results @[visualize_smpl_calibration](https://github.com/open-mmlab/mmhuman3d/blob/20a1c620ce7be0b7811299b2e471999922a4fbba/demo/estimate_smpl_image.py#L98).  

The video has just 300 frames.

**Comment by ttxskk** [comment]
Sorry for the late reply. The OOM error has been fixed in #134. Please check it.

**Comment by rlleshi** [comment]
Nice, thanks. It works (even though barely, 99% RAM usage).

But then come CUDA (8G) OOM:

```
Load checkpoint from local path: data/checkpoints/resnet50_hmr_pw3d-04f40f58_20211201.pth
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 374/374, 6.9 task/s, elapsed: 54s, ETA:     0s
Overwriting work_dir/images and its files.
Running "ffmpeg -y -f rawvideo -s 3840x2160 -pix_fmt bgr24 -loglevel error -threads 4 -i - -f image2 -start_number 0 work_dir/images/%06d.png"
/home/rejnald/.pyenv/versions/mmhuman3d/lib/python3.8/site-packages/smplx/body_models.py:137: DeprecationWarning: Please use `csc_matrix` from the `scipy.sparse` namespace, the `scipy.sparse.csc` namespace is deprecated.
  data_struct = Struct(**pickle.load(smpl_file,
WARNING: You are using a SMPL model, with only 10 shape coefficients.
Make dir work_dir/results/
  0%|                                                                                                                                                                                                                                                              | 0/37 [00:58<?, ?it/s]
Traceback (most recent call last):
  File "demo/estimate_smpl_image.py", line 326, in <module>
    main(args)
  File "demo/estimate_smpl_image.py", line 231, in main
    single_person_with_mmdet(args, frames_iter)
  File "demo/estimate_smpl_image.py", line 100, in single_person_with_mmdet
    visualize_smpl_hmr(
  File "/home/rejnald/projects/wizai/vortanz/3D-pose/mmhuman3d/mmhuman3d/core/visualization/visualize_smpl.py", line 1114, in visualize_smpl_hmr
    return func(Ks=Ks, K=K, T=T, **kwargs)
  File "/home/rejnald/projects/wizai/vortanz/3D-pose/mmhuman3d/mmhuman3d/core/visualization/visualize_smpl.py", line 1036, in render_smpl
    results = render_runner.render(
  File "/home/rejnald/projects/wizai/vortanz/3D-pose/mmhuman3d/mmhuman3d/core/visualization/renderer/torch3d_renderer/render_runner.py", line 111, in render
    images_batch = renderer(indexes=indexes, **foward_params_batch)
  File "/home/rejnald/.pyenv/versions/mmhuman3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rejnald/projects/wizai/vortanz/3D-pose/mmhuman3d/mmhuman3d/core/visualization/renderer/torch3d_renderer/smpl_renderer.py", line 184, in forward
    rendered_tensor = self.image_renderer(
  File "/home/rejnald/.pyenv/versions/mmhuman3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rejnald/projects/wizai/vortanz/3D-pose/mmhuman3d/mmhuman3d/core/visualization/renderer/torch3d_renderer/mesh_renderer.py", line 78, in forward
    rendered_images = self.shader(
  File "/home/rejnald/.pyenv/versions/mmhuman3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rejnald/.pyenv/versions/mmhuman3d/lib/python3.8/site-packages/pytorch3d/renderer/mesh/shader.py", line 149, in forward
    colors = phong_shading(
  File "/home/rejnald/.pyenv/versions/mmhuman3d/lib/python3.8/site-packages/pytorch3d/renderer/mesh/shading.py", line 84, in phong_shading
    pixel_coords = interpolate_face_attributes(
  File "/home/rejnald/.pyenv/versions/mmhuman3d/lib/python3.8/site-packages/pytorch3d/ops/interp_face_attrs.py", line 60, in interpolate_face_attributes
    out = _InterpFaceAttrs.apply(*args)
  File "/home/rejnald/.pyenv/versions/mmhuman3d/lib/python3.8/site-packages/pytorch3d/ops/interp_face_attrs.py", line 70, in forward
    return _C.interp_face_attrs_forward(*args)
RuntimeError: CUDA out of memory. Tried to allocate 950.00 MiB (GPU 0; 7.80 GiB total capacity; 4.35 GiB already allocated; 768.56 MiB free; 4.42 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

I think that the CUDA memory is never cleared after the initial inference (which takes almost 3G). Maybe clearing that might help?

**Comment by rlleshi** [comment]
Nice, thanks. It works (even though barely @ 99% RAM usage).

But then comes a CUDA (8G) OOM:
```

Load checkpoint from local path: data/checkpoints/resnet50_hmr_pw3d-04f40f58_20211201.pth
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 374/374, 6.9 task/s, elapsed: 54s, ETA:     0s
Overwriting work_dir/images and its files.
Running "ffmpeg -y -f rawvideo -s 3840x2160 -pix_fmt bgr24 -loglevel error -threads 4 -i - -f image2 -start_number 0 work_dir/images/%06d.png"
.pyenv/versions/mmhuman3d/lib/python3.8/site-packages/smplx/body_models.py:137: DeprecationWarning: Please use `csc_matrix` from the `scipy.sparse` namespace, the `scipy.sparse.csc` namespace is deprecated.
  data_struct = Struct(**pickle.load(smpl_file,
WARNING: You are using a SMPL model, with only 10 shape coefficients.
Make dir work_dir/results/
  0%|                                                                                                                                                                                                                                                              | 0/37 [00:58<?, ?it/s]
Traceback (most recent call last):
  File "demo/estimate_smpl_image.py", line 326, in <module>
    main(args)
  File "demo/estimate_smpl_image.py", line 231, in main
    single_person_with_mmdet(args, frames_iter)
  File "demo/estimate_smpl_image.py", line 100, in single_person_with_mmdet
    visualize_smpl_hmr(
  File "mmhuman3d/mmhuman3d/core/visualization/visualize_smpl.py", line 1114, in visualize_smpl_hmr
    return func(Ks=Ks, K=K, T=T, **kwargs)
  File "mmhuman3d/mmhuman3d/core/visualization/visualize_smpl.py", line 1036, in render_smpl
    results = render_runner.render(
  File "mmhuman3d/mmhuman3d/core/visualization/renderer/torch3d_renderer/render_runner.py", line 111, in render
    images_batch = renderer(indexes=indexes, **foward_params_batch)
  File ".pyenv/versions/mmhuman3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "mmhuman3d/mmhuman3d/core/visualization/renderer/torch3d_renderer/smpl_renderer.py", line 184, in forward
    rendered_tensor = self.image_renderer(
  File ".pyenv/versions/mmhuman3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "mmhuman3d/mmhuman3d/core/visualization/renderer/torch3d_renderer/mesh_renderer.py", line 78, in forward
    rendered_images = self.shader(
  File ".pyenv/versions/mmhuman3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File ".pyenv/versions/mmhuman3d/lib/python3.8/site-packages/pytorch3d/renderer/mesh/shader.py", line 149, in forward
    colors = phong_shading(
  File ".pyenv/versions/mmhuman3d/lib/python3.8/site-packages/pytorch3d/renderer/mesh/shading.py", line 84, in phong_shading
    pixel_coords = interpolate_face_attributes(
  File ".pyenv/versions/mmhuman3d/lib/python3.8/site-packages/pytorch3d/ops/interp_face_attrs.py", line 60, in interpolate_face_attributes
    out = _InterpFaceAttrs.apply(*args)
  File ".pyenv/versions/mmhuman3d/lib/python3.8/site-packages/pytorch3d/ops/interp_face_attrs.py", line 70, in forward
    return _C.interp_face_attrs_forward(*args)
RuntimeError: CUDA out of memory. Tried to allocate 950.00 MiB (GPU 0; 7.80 GiB total capacity; 4.35 GiB already allocated; 768.56 MiB free; 4.42 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
I think that the CUDA memory is never cleared after the initial inference (which takes almost 3G). Maybe clearing that might help?

**Comment by ttxskk** [comment]
Yes, it can reduce the dependence on GPU memory. Additionally, you can choose a suitable batch size for visualization according to the available GPU memory.
