### ISSUE TITLE
ParametricMesh error on estimate_smpl demo

### ISSUE THREAD

**Issue by codeHorasan** [open-mmlab/mmhuman3d#217]
I was trying to run the estimate_smpl. After handling module errors, I'm stuck with this error:
KeyError: 'ParametricMesh is not in the architectures registry'

with:
python demo/estimate_smpl.py hmr_res50_mixed_224x224.py hmr_mesh_224x224-c21e8229_20201015.pth --single_person_demo --det_config faster_rcnn_r50_fpn_coco.py --det_checkpoint faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth --input_path human.jpg --output /output/ --show_path /output/ --device CPU

Any suggestions?

**Comment by ttxskk** [comment]
Hi, this error looks weird. I run the `estimate_smpl.py` as follows:
```shell
python demo/estimate_smpl.py configs/hmr/resnet50_hmr_pw3d.py data/checkpoints/hmr.pth --single_person_demo --det_config demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py --det_checkpoint https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth --input_path demo/resources/S1_Directions_1.54138969_000001.jpg --output output/ --show_path output/ --device cpu
```
Everything looks well to me. I think you can create a new branch from MMHuman3D and try to run `estimate_smpl.py` again.

**Comment by codeHorasan** [comment]
Hello, I was able to solve that problem but now I am getting "RuntimeError: Not compiled with GPU support" from Pytorch3d on meshes.

Traceback (most recent call last):
  File "estimate_smpl.py", line 591, in <module>
    main(args)
  File "estimate_smpl.py", line 489, in main
    single_person_with_mmdet(args, frames_iter)
  File "estimate_smpl.py", line 278, in single_person_with_mmdet
    visualize_smpl_hmr(
  File "C:\Users\ugur_\OneDrive\Belgeler\mmhuman3d\mmhuman3d\core\visualization\visualize_smpl.py", line 1120, in visualize_smpl_hmr
    return func(Ks=Ks, K=K, T=T, **kwargs)
  File "C:\Users\ugur_\OneDrive\Belgeler\mmhuman3d\mmhuman3d\core\visualization\visualize_smpl.py", line 1041, in render_smpl
    results = render_runner.render(
  File "C:\Users\ugur_\OneDrive\Belgeler\mmhuman3d\mmhuman3d\core\renderer\torch3d_renderer\render_runner.py", line 115, in render
    images_batch = renderer(indexes=indexes, **foward_params_batch)
  File "C:\Users\ugur_\.conda\envs\open-mmlab\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\ugur_\OneDrive\Belgeler\mmhuman3d\mmhuman3d\core\renderer\torch3d_renderer\smpl_renderer.py", line 182, in forward
    rendered_tensor = self.image_renderer(
  File "C:\Users\ugur_\.conda\envs\open-mmlab\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\ugur_\OneDrive\Belgeler\mmhuman3d\mmhuman3d\core\renderer\torch3d_renderer\mesh_renderer.py", line 71, in forward
    fragments = self.rasterizer(meshes_world=meshes, cameras=cameras)
  File "C:\Users\ugur_\.conda\envs\open-mmlab\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\ugur_\.conda\envs\open-mmlab\lib\site-packages\pytorch3d-0.6.2-py3.8-win-amd64.egg\pytorch3d\renderer\mesh\rasterizer.py", line 240, in forward
    pix_to_face, zbuf, bary_coords, dists = rasterize_meshes(
  File "C:\Users\ugur_\.conda\envs\open-mmlab\lib\site-packages\pytorch3d-0.6.2-py3.8-win-amd64.egg\pytorch3d\renderer\mesh\rasterize_meshes.py", line 234, in rasterize_meshes
    pix_to_face, zbuf, barycentric_coords, dists = _RasterizeFaceVerts.apply(
  File "C:\Users\ugur_\.conda\envs\open-mmlab\lib\site-packages\pytorch3d-0.6.2-py3.8-win-amd64.egg\pytorch3d\renderer\mesh\rasterize_meshes.py", line 308, in forward
    pix_to_face, zbuf, barycentric_coords, dists = _C.rasterize_meshes(
RuntimeError: Not compiled with GPU support

I am using CPU, do I have a chance to run it on CPU?
