### ISSUE TITLE
SmoothNet Demo Memory Error

### ISSUE THREAD

**Issue by rlleshi** [open-mmlab/mmhuman3d#221]
Traceback (most recent call last):
  File "demo/estimate_smpl.py", line 595, in <module>
    main(args)
  File "demo/estimate_smpl.py", line 493, in main
    single_person_with_mmdet(args, frames_iter)
  File "demo/estimate_smpl.py", line 221, in single_person_with_mmdet
    verts = smooth_process(verts, smooth_type=args.smooth_type)
  File "mmhuman3d/mmhuman3d/utils/demo_utils.py", line 356, in smooth_process
    x = smooth_func(x)
  File "mmhuman3d/mmhuman3d/core/post_processing/smooth/smoothnet.py", line 224, in __call__
    smoothed = self.smoothnet(x)  # in shape [1, KC, T]
  File "/.pyenv/versions/mmhuman3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "mmhuman3d/mmhuman3d/core/post_processing/smooth/smoothnet.py", line 124, in forward
    x = self.encoder(x)
  File "/.pyenv/versions/mmhuman3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/.pyenv/versions/mmhuman3d/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/.pyenv/versions/mmhuman3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/.pyenv/versions/mmhuman3d/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/.pyenv/versions/mmhuman3d/lib/python3.8/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: [enforce fail at CPUAllocator.cpp:68] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 113788846080 bytes. Error code 12 (Cannot allocate memory)

**Comment by ttxskk** [comment]
Hi, this error looks like due to limited memory? I don't meet this error when running `estimate_smpl.py`.

**Comment by ttxskk** [comment]
This looks weird, I'll check it.

**Comment by Fubuki901** [comment]
I met this memory situation as well, but the program exit correctly.

**Comment by wmj142326** [comment]
我也出现了同样的内存错误，单人姿态估计运行没问题，
但是多人视频时间过长会报错，python被kill掉了；我把视频时间变短才运行成功。

“demo/estimate_smpl.py”的第394行出现问题：
verts = smooth_process(verts, smooth_type=args.smooth_type)

进入“mmhuman3d/utils/demo_utils.py“的smooth_process（）”，在352行：

 if x.ndim == 4:
        for i in range(x.shape[1]):
            x[:, i] = smooth_func(x[:, i])
            
 这里占用了大量的内存。
