### ISSUE TITLE
FileNotFoundError: data/checkpoints/hrnet_w32_conv_pare_mosh.pth can not be found.

### ISSUE THREAD

**Issue by GKeppler** [open-mmlab/mmhuman3d#254]
FileNotFoundError: data/checkpoints/hrnet_w32_conv_pare_mosh.pth can not be found.

The above checkpoint is not mentioned in run the demo on a offline video:

python demo/webcam_demo.py --synchronous true --cam-id=/../mmhuman3d/WIN_20220925_21_10_40_Pro.mp4

Full log:
WARNING: You are using a SMPL model, with only 10 shape coefficients.
load checkpoint from http path: https://download.openmmlab.com/mmdetection/v2.0/ssd/ssdlite_mobilenetv2_scratch_600e_coco/ssdlite_mobilenetv2_scratch_600e_coco_20210629_110627-974d9307.pth
WARNING: You are using a SMPL model, with only 10 shape coefficients.
WARNING: You are using a SMPL model, with only 10 shape coefficients.
load checkpoint from local path: data/checkpoints/hrnet_w32_conv_pare_mosh.pth
Traceback (most recent call last):
  File "demo/webcam_demo.py", line 418, in <module>
    main()
  File "demo/webcam_demo.py", line 367, in main
    mesh_model, extractor = init_model(
  File "/home/gustav/git/mmhuman3d/mmhuman3d/apis/inference.py", line 37, in init_model
    load_checkpoint(model, checkpoint, map_location=device)
  File "/home/gustav/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 617, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/home/gustav/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 552, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/home/gustav/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 299, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/home/gustav/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 317, in load_from_local
    raise FileNotFoundError(f'{filename} can not be found.')
FileNotFoundError: data/checkpoints/hrnet_w32_conv_pare_mosh.pth can not be found.

**Comment by ttxskk** [comment]
Hi @GKeppler , you can download this checkpoint from [model-zoo](https://github.com/open-mmlab/mmhuman3d/blob/main/docs/model_zoo.md).

**Comment by GKeppler** [comment]
Thank you for your answer. However, the specific file "hrnet_w32_conv_pare_mosh.pth" is not in the checkpoints

**Comment by ttxskk** [comment]
Hi @GKeppler,
For a specific checkpoint, such as `hrnet_w32_conv_pare_mosh.pth`, you should click the hyperlink (PARE) on the model-zoo page, which will take you to the page for PARE. After that, you can find the checkpoint you need at the **Results and Models**.  Please check it more carefully.
