### ISSUE TITLE
No module named 'mmhuman3d.core.renderer.mpr_renderer.cuda.rasterizer'

### ISSUE THREAD

**Issue by vpromise** [open-mmlab/mmhuman3d#300]
when I run 
`python demo/webcam_demo.py
`
It outputs
`
Please reinstall MMHuman3D to build mpr_renderer.
Traceback (most recent call last):
  File "demo/webcam_demo.py", line 14, in <module>
    from mmhuman3d.core.renderer.mpr_renderer.smpl_realrender import \
  File "/home/v/Work/mmhuman3d/mmhuman3d/core/renderer/mpr_renderer/smpl_realrender.py", line 6, in <module>
    from mmhuman3d.core.renderer.mpr_renderer.rasterizer import \
  File "/home/v/Work/mmhuman3d/mmhuman3d/core/renderer/mpr_renderer/rasterizer.py", line 4, in <module>
    from mmhuman3d.core.renderer.mpr_renderer.cuda.rasterizer import \
ModuleNotFoundError: No module named 'mmhuman3d.core.renderer.mpr_renderer.cuda.rasterizer'
`
but reinstall MMHuman3D not works

**Comment by ttxskk** [comment]
Hi @vpromise, please check if you have successfully installed the `mpr_renderer`.

**Comment by jensnowww** [comment]
I'm having the same, issue. Is it possible to reinstall just this part?

**Comment by pengfeiz-flwls** [comment]
Same issue. Have you figured out how to solve it? I tried search mpr_renderer but nothing found
