### ISSUE TITLE
Error when estimate SMPL parameters for single-person when input is image.

### ISSUE THREAD

**Issue by zhang123-sys** [open-mmlab/mmhuman3d#313]
![image](https://user-images.githubusercontent.com/63956071/218713269-167b1563-0a56-45a9-aa34-968413075fd9.png)

**Comment by zhang123-sys** [comment]
Traceback (most recent call last):
  File "demo/estimate_smpl.py", line 595, in <module>
    main(args)
  File "demo/estimate_smpl.py", line 493, in main
    single_person_with_mmdet(args, frames_iter)
  File "demo/estimate_smpl.py", line 210, in single_person_with_mmdet
    smpl_poses = speed_up_process(
  File "E:\gait-recognition\mmhuman3d-0.10.0\demo\mmhuman3d\utils\demo_utils.py", line 434, in speed_up_process
    x = speed_up_func(x)
  File "E:\gait-recognition\mmhuman3d-0.10.0\demo\mmhuman3d\core\post_processing\speed_up\deciwatch.py", line 56, in __call__
    assert seq_len > self.slide_window_size
AssertionError

**Comment by ttxskk** [comment]
Hi @zhang123-sys,

The log means the length of the input sequence should larger than slide_window_size. So you should disable the smooth algorithm if the input is a single image. 

I hope this answer is helpful to you.
