### ISSUE TITLE
TypeError: convert_by_mode() got an unexpected keyword argument 'enable_multi_human_data'

### ISSUE THREAD

**Issue by github1838** [open-mmlab/mmhuman3d#320]
When I use the command to convert pw3d for HMR,this error is thrown:

[pw3d] Converting ...
Traceback (most recent call last):
  File "tools/convert_datasets.py", line 117, in <module>
    main()
  File "tools/convert_datasets.py", line 109, in main
    data_converter.convert(
  File "/home/wz/mmcv/mmhuman3d/mmhuman3d/data/data_converters/base_converter.py", line 97, in convert
    self.convert_by_mode(dataset_path, out_path, mode, *args, **kwargs)
TypeError: convert_by_mode() got an unexpected keyword argument 'enable_multi_human_data'

The same thing happens on all datasets except coco, such as pw3d, mpii, mpi_inf_3dhp, lsp_original.I ' m confused. I can 't find the mistake.

**Comment by github1838** [comment]
I annotated that parameter.
