### ISSUE TITLE
when I try to run webcam_demo,Imeet this question.ImportError: /home/lia/anaconda3/envs/mmlab/lib/python3.8/site-packages/pytorch3d/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jS2_

### ISSUE THREAD

**Issue by lllllialois** [open-mmlab/mmhuman3d#330]
```
Traceback (most recent call last):
  File "demo/webcam_demo.py", line 13, in <module>
    from mmhuman3d.apis import inference_image_based_model, init_model
  File "/home/lia/projects/mmhuman3d/mmhuman3d/apis/__init__.py", line 1, in <module>
    from mmhuman3d.apis import inference, test, train
  File "/home/lia/projects/mmhuman3d/mmhuman3d/apis/inference.py", line 12, in <module>
    from mmhuman3d.models.architectures.builder import build_architecture
  File "/home/lia/projects/mmhuman3d/mmhuman3d/models/architectures/builder.py", line 6, in <module>
    from .expressive_mesh_estimator import SMPLXImageBodyModelEstimator
  File "/home/lia/projects/mmhuman3d/mmhuman3d/models/architectures/expressive_mesh_estimator.py", line 18, in <module>
    from ..heads.builder import build_head
  File "/home/lia/projects/mmhuman3d/mmhuman3d/models/heads/builder.py", line 9, in <module>
    from .pymafx_head import PyMAFXHead, Regressor
  File "/home/lia/projects/mmhuman3d/mmhuman3d/models/heads/pymafx_head.py", line 33, in <module>
    from mmhuman3d.utils.camera_utils import homo_vector
  File "/home/lia/projects/mmhuman3d/mmhuman3d/utils/camera_utils.py", line 7, in <module>
    from pytorch3d.renderer.cameras import CamerasBase
  File "/home/lia/anaconda3/envs/mmlab/lib/python3.8/site-packages/pytorch3d/renderer/__init__.py", line 7, in <module>
    from .blending import (
  File "/home/lia/anaconda3/envs/mmlab/lib/python3.8/site-packages/pytorch3d/renderer/blending.py", line 10, in <module>
    from pytorch3d import _C
ImportError: /home/lia/anaconda3/envs/mmlab/lib/python3.8/site-packages/pytorch3d/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jS2_
```

my environment is below and my cuda is 11.0, and I have to uninstall mvcc-full and install it again, but it doesn't work

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
addict                    2.4.0                    pypi_0    pypi
astropy                   5.2.1                    pypi_0    pypi
attributee                0.1.5                    pypi_0    pypi
attrs                     22.2.0                   pypi_0    pypi
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2023.01.10           h06a4308_0    defaults
cdflib                    0.3.20                   pypi_0    pypi
certifi                   2022.12.7        py38h06a4308_0    defaults
chumpy                    0.70                     pypi_0    pypi
colorlog                  6.7.0                    pypi_0    pypi
colormap                  1.0.4                    pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
cudatoolkit               11.0.221             h6bb024c_0    defaults
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.33                  pypi_0    pypi
deprecated                1.2.13                   pypi_0    pypi
dotty-dict                1.3.1                    pypi_0    pypi
easydev                   0.12.1                   pypi_0    pypi
einops                    0.6.0                    pypi_0    pypi
ffmpeg                    4.2.2                h20bf706_0    defaults
fonttools                 4.39.2                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0    defaults
fvcore                    0.1.5.post20210915            py38    https://conda.anaconda.org/fvcore
giflib                    5.2.1                h5eee18b_3    defaults
gmp                       6.2.1                h295c915_3    defaults
gnutls                    3.6.15               he1e5248_0    defaults
h5py                      3.8.0                    pypi_0    pypi
imageio                   2.27.0                   pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
iopath                    0.1.9                      py38    https://conda.anaconda.org/iopath
jpeg                      9e                   h5eee18b_1    defaults
json-tricks               3.16.1                   pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
lame                      3.100                h7b6447c_0    defaults
lap                       0.4.0                    pypi_0    pypi
lazy-loader               0.2                      pypi_0    pypi
lcms2                     2.12                 h3be6417_0    defaults
ld_impl_linux-64          2.38                 h1181459_1    defaults
lerc                      3.0                  h295c915_0    defaults
libdeflate                1.17                 h5eee18b_0    defaults
libffi                    3.4.2                h6a678d5_6    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libidn2                   2.3.2                h7f8727e_0    defaults
libopus                   1.3.1                h7b6447c_0    defaults
libpng                    1.6.39               h5eee18b_0    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
libtasn1                  4.16.0               h27cfd23_0    defaults
libtiff                   4.5.0                h6a678d5_2    defaults
libunistring              0.9.10               h27cfd23_0    defaults
libvpx                    1.7.0                h439df22_0    defaults
libwebp                   1.2.4                h11a3e52_1    defaults
libwebp-base              1.2.4                h5eee18b_1    defaults
lz4-c                     1.9.4                h6a678d5_0    defaults
matplotlib                3.7.1                    pypi_0    pypi
mmcls                     0.23.2                   pypi_0    pypi
mmcv-full                 1.5.3                    pypi_0    pypi
mmdet                     2.25.1                   pypi_0    pypi
mmhuman3d                 0.10.0                    dev_0    <develop>
mmpose                    0.28.1                   pypi_0    pypi
mmtrack                   0.13.0                   pypi_0    pypi
motmetrics                1.4.0                    pypi_0    pypi
munkres                   1.1.4                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0    defaults
nettle                    3.7.3                hbbd107a_1    defaults
networkx                  3.0                      pypi_0    pypi
numpy                     1.24.2                   pypi_0    pypi
nvidiacub                 1.10.0                        0    https://conda.anaconda.org/bottler
opencv-python             4.7.0.72                 pypi_0    pypi
openh264                  2.1.1                h4ff587b_0    defaults
openssl                   1.1.1t               h7f8727e_0    defaults
packaging                 23.0                     pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickle5                   0.0.11                   pypi_0    pypi
pillow                    9.4.0                    pypi_0    pypi
pip                       23.0.1           py38h06a4308_0    defaults
plyfile                   0.8.1                    pypi_0    pypi
portalocker               2.3.0            py38h06a4308_0    defaults
ptyprocess                0.7.0                    pypi_0    pypi
pycocotools               2.0.2                    pypi_0    pypi
pyerfa                    2.0.0.3                  pypi_0    pypi
pygments                  2.14.0                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.8.16               h7a1cb2a_3    defaults
python-dateutil           2.8.2                    pypi_0    pypi
pytorch3d                 0.7.2                    pypi_0    pypi
pytz                      2023.2                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0              py38h5eee18b_1    defaults
readline                  8.2                  h5eee18b_0    defaults
rtree                     1.0.1                    pypi_0    pypi
scikit-image              0.20.0                   pypi_0    pypi
scipy                     1.9.1                    pypi_0    pypi
seaborn                   0.12.2                   pypi_0    pypi
setuptools                67.6.0                   pypi_0    pypi
smplx                     0.1.28                   pypi_0    pypi
sqlite                    3.41.1               h5eee18b_0    defaults
tabulate                  0.8.10           py38h06a4308_0    defaults
termcolor                 2.1.0            py38h06a4308_0    defaults
terminaltables            3.1.10                   pypi_0    pypi
tifffile                  2023.3.21                pypi_0    pypi
tk                        8.6.12               h1ccaba5_0    defaults
torch                     1.7.1+cu110              pypi_0    pypi
torchaudio                0.7.2                    pypi_0    pypi
torchvision               0.8.2+cu110              pypi_0    pypi
tqdm                      4.65.0           py38hb070fc8_0    defaults
trimesh                   3.21.2                   pypi_0    pypi
typing-extensions         4.5.0                    pypi_0    pypi
vedo                      2023.4.4                 pypi_0    pypi
vtk                       9.2.6                    pypi_0    pypi
wheel                     0.38.4           py38h06a4308_0    defaults
wrapt                     1.15.0                   pypi_0    pypi
x264                      1!157.20191217       h7b6447c_0    defaults
xmltodict                 0.13.0                   pypi_0    pypi
xtcocotools               1.13                     pypi_0    pypi
xz                        5.2.10               h5eee18b_1    defaults
yacs                      0.1.6              pyhd3eb1b0_1    defaults
yaml                      0.2.5                h7b6447c_0    defaults
yapf                      0.32.0                   pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0    defaults
zstd                      1.5.2                ha4553b6_0    defaults
```

**Comment by chaitanya100100** [comment]
Did you manage to solve it?
