### ISSUE TITLE
pytorch3d Installation unsuccessful

### ISSUE THREAD

**Issue by shihzenq** [open-mmlab/mmhuman3d#360]
1、conda install pytorch3d -c pytorch3d 
     This installation has been unsuccessful，then I used another way to install pytorch3d.
2、git clone https://github.com/facebookresearch/pytorch3d.git
cd pytorch3d
pip install .

error: 
 Traceback (most recent call last):
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1667, in _run_ninja_build
          subprocess.run(
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/data/pytorch3d/setup.py", line 144, in <module>
          setup(
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
          _build_ext.build_ext.run(self)
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
          build_ext.build_extensions(self)
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
          _build_ext.build_ext.build_extensions(self)
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 529, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1354, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/opt/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pytorch3d
  Running setup.py clean for pytorch3d
Failed to build pytorch3d
ERROR: Could not build wheels for pytorch3d, which is required to install pyproject.toml-based projects

**Comment by gucaslyz** [comment]
git clone https://github.com/facebookresearch/pytorch3d.git
cd pytorch3d && pip install -e .

**Comment by Dipankar1997161** [comment]
> git clone https://github.com/facebookresearch/pytorch3d.git cd pytorch3d && pip install -e .

this definitely works

**Comment by ThanosUTH** [comment]
does not work for me


  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of pytorch3d
  Moving to /home/thanos/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/pytorch3d-0.3.0.dist-info/
   from /home/thanos/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/~ytorch3d-0.3.0.dist-info
  Moving to /home/thanos/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/pytorch3d/
   from /home/thanos/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/~ytorch3d
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [285 lines of output]
    running develop
    running egg_info
    creating pytorch3d.egg-info
    writing pytorch3d.egg-info/PKG-INFO
    writing dependency_links to pytorch3d.egg-info/dependency_links.txt
    writing entry points to pytorch3d.egg-info/entry_points.txt
    writing requirements to pytorch3d.egg-info/requires.txt
    writing top-level names to pytorch3d.egg-info/top_level.txt
    writing manifest file 'pytorch3d.egg-info/SOURCES.txt'
    reading manifest file 'pytorch3d.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    adding license file 'LICENSE-3RD-PARTY'
    writing manifest file 'pytorch3d.egg-info/SOURCES.txt'
    running build_ext
    building 'pytorch3d._C' extension
