### ISSUE TITLE
Error in multi-person demo even with Docker

### ISSUE THREAD

**Issue by Keiku** [open-mmlab/mmhuman3d#399]
@caizhongang 

I created the following Dockerfile.
https://github.com/Keiku/docker-mmhuman3d

The single person demo below worked fine.
```
python demo/estimate_smpl.py \
    configs/hmr/resnet50_hmr_pw3d.py \
    data/checkpoints/resnet50_hmr_pw3d-04f40f58_20211201.pth \
    --single_person_demo \
    --det_config demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \
    --det_checkpoint https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    --input_path  demo/resources/single_person_demo.mp4 \
    --show_path vis_results/single_person_demo.mp4 \
    --output demo_result \
    --smooth_type savgol \
    --speed_up_type deciwatch \
    --draw_bbox
```

The following error occurred in the multi-person demo. I think the problem is probably a package conflict, but how can I solve it?

```python
root@d3ce02be5687:~/mmhuman3d# python demo/estimate_smpl.py \
>     configs/hmr/resnet50_hmr_pw3d.py \
>     data/checkpoints/resnet50_hmr_pw3d.pth \
>     --multi_person_demo \
>     --tracking_config demo/mmtracking_cfg/deepsort_faster-rcnn_fpn_4e_mot17-private-half.py \
>     --input_path  demo/resources/multi_person_demo.mp4 \
>     --show_path vis_results/multi_person_demo.mp4 \
>     --smooth_type savgol \
>     --speed_up_type deciwatch \
>     --draw_bbox 
/usr/local/lib/python3.9/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "/home/docker/mmhuman3d/demo/estimate_smpl.py", line 12, in <module>
    from mmhuman3d.apis import (
  File "/home/docker/mmhuman3d/mmhuman3d/apis/__init__.py", line 1, in <module>
    from mmhuman3d.apis import inference, test, train
  File "/home/docker/mmhuman3d/mmhuman3d/apis/inference.py", line 11, in <module>
    from mmhuman3d.data.datasets.pipelines import Compose
  File "/home/docker/mmhuman3d/mmhuman3d/data/datasets/__init__.py", line 2, in <module>
    from .base_dataset import BaseDataset
  File "/home/docker/mmhuman3d/mmhuman3d/data/datasets/base_dataset.py", line 7, in <module>
    from .pipelines import Compose
  File "/home/docker/mmhuman3d/mmhuman3d/data/datasets/pipelines/__init__.py", line 11, in <module>
    from .hybrik_transforms import (
  File "/home/docker/mmhuman3d/mmhuman3d/data/datasets/pipelines/hybrik_transforms.py", line 9, in <module>
    from mmhuman3d.utils.demo_utils import box2cs, xyxy2xywh
  File "/home/docker/mmhuman3d/mmhuman3d/utils/demo_utils.py", line 11, in <module>
    from scipy import interpolate
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/usr/local/lib/python3.9/site-packages/scipy/__init__.py", line 134, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.9/site-packages/scipy/interpolate/__init__.py", line 167, in <module>
    from ._interpolate import *
  File "/usr/local/lib/python3.9/site-packages/scipy/interpolate/_interpolate.py", line 14, in <module>
    from . import _fitpack_py
  File "/usr/local/lib/python3.9/site-packages/scipy/interpolate/_fitpack_py.py", line 8, in <module>
    from ._fitpack_impl import bisplrep, bisplev, dblint  # noqa: F401
  File "/usr/local/lib/python3.9/site-packages/scipy/interpolate/_fitpack_impl.py", line 103, in <module>
    'iwrk': array([], dfitpack_int), 'u': array([], float),
TypeError
root@d3ce02be5687:~/mmhuman3d# 
```

**Comment by Keiku** [comment]
@Wei-Chen-hub 
Do you have any insight into the above issues?
