### ISSUE TITLE
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

### ISSUE THREAD

**Issue by ZhengtianXu** [open-mmlab/mmhuman3d#53]
For training models, I met this problem. Anyone has some solutions?

**Comment by caizhongang** [comment]
Hi @ZhengtianXu , it seems to be a `DistributedDataParallel` issue, please elaborate how did you run the training.

**Comment by ZhengtianXu** [comment]
> 

Hi, @caizhongang I can run demo successfully, when I run training code with 1 gpu, it raises

```
2021-12-28 15:26:52,839 - mmhuman3d - INFO - workflow: [('train', 1)], max: 10 epochs
2021-12-28 15:26:52,840 - mmhuman3d - INFO - Checkpoints will be saved to /home/zhengtian/mm3dhuman/mmhuman3d/hmr_training by HardDiskBackend.
Traceback (most recent call last):
  File "tools/train.py", line 154, in <module>
    main()
  File "tools/train.py", line 142, in main
    train_model(
  File "/home/zhengtian/mm3dhuman/mmhuman3d/mmhuman3d/apis/train.py", line 168, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "/home/zhengtian/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/zhengtian/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/zhengtian/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/home/zhengtian/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/zhengtian/mm3dhuman/mmhuman3d/mmhuman3d/models/architectures/mesh_estimator.py", line 143, in train_step
    features = self.backbone(img)
  File "/home/zhengtian/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhengtian/mm3dhuman/mmhuman3d/mmhuman3d/models/backbones/resnet.py", line 620, in forward
    x = self.norm1(x)
  File "/home/zhengtian/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhengtian/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 731, in forward
    world_size = torch.distributed.get_world_size(process_group)
  File "/home/zhengtian/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 748, in get_world_size
    return _get_group_size(group)
  File "/home/zhengtian/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 274, in _get_group_size
    default_pg = _get_default_group()
  File "/home/zhengtian/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 358, in _get_default_group
    raise RuntimeError("Default process group has not been initialized, "
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
```

**Comment by mingyuan-zhang** [comment]
Hi, I think this is caused by the incomplete DDP environment. Maybe you can try DP training. You can refer this script for it:


```Shell
CONFIG=$1
GPUS=$2
PORT=${PORT:-29500}

PYTHONPATH="$(dirname $0)/..":$PYTHONPATH \
python -m torch.distributed.launch --nproc_per_node=$GPUS --master_port=$PORT \
    $(dirname "$0")/train.py $CONFIG --launcher pytorch ${@:3}
```

**Comment by ZhengtianXu** [comment]
Solved with 
```
dist.init_process_group('gloo', init_method='file:///tmp/somefile', rank=0, world_size=1)
```
